services:
  nextjs:
    build: .
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/home/node/app
    environment:
      - DJANGO_API_URL= http://host.docker.internal:8000/api
      # - DJANGO_API_URL=http://34.200.44.25:8000/api
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
# /etc/hosts

#IP do gateway host.docker.internal

#127.0.0.1 host.docker.internal
